apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: 507453150539.dkr.ecr.us-east-1.amazonaws.com/tasky
        env:
        - name: MONGODB_URI
          value: "TEMP"
        env:
        - name: SECRET_KEY
          value: "TEMP"            
        ports:
        - containerPort: 8080
